### ISSUE TITLE
[FEAT] A more detailed ARRAY after epub parsing

### ISSUE THREAD

**Issue by HanslettTheDev** [sws2apps/jw-epub-parser#967]
**Is your feature request related to a problem? Please describe.**
 Currently, I can get all the meeting parts well, but I would wish to get other aspects separately, like the student counsel point and time for each part. Rather than it merged with one part completely

**Describe the solution you'd like**
Here is a sample json structure I have for my desktop application I built for the same purpose(though jw-epub-parser does the parsing better)
```json
{
    "September 2-8": {
        "month": "September 2-8",
        "reading": "PSALMS 79-81",
        "opening_song": "Song 29",
        "fine_fine_lesson": "Show Love for Jehovah Wonderful Name",
        "bible_reading": "Ps 79:1\u201380:7",
        "preaching": [
            "When You De Start Discussion",
            "When You De Start Discussion",
            "When You De Start Discussion",
            "When You De Check the Person Again"
        ],
        "preaching_time": [
            "1 ",
            "3 ",
            "2 ",
            "5 "
        ],
        "middle_song": "Song 10",
        "middle_parts": [
            "\u201cThem Go Make My Name Dey Holy\u201d"
        ],
        "middle_parts_time": [
            "15"
        ],
        "book_study": "bt chap. 15 \u00b61-7, and introduction to part 6",
        "book_study_box": "",
        "concluding_song": "Song 90"
    },
```

**Additional context**
I have my [software](https://github.com/HanslettTheDev/NWBS-Desktop/), which I built in Python, including a web scrapper that fetches information from our website and generates a meeting schedule. But it's challenging to keep making those adjustments since the website receives lots of updates. So, I searched for a tool and stumbled across yours. Excellent work, by the way.  It parsed the pidgin language flawlessly

**Comment by rhahao** [comment]
Hello @HanslettTheDev, thanks for reaching out.

While we could not change the current structure of the parsing result (since this package is used by other tools as well), we could enable the pidgin language for [enhanced parsing](https://github.com/sws2apps/jw-epub-parser?tab=readme-ov-file#with-enhanced-parsing) so that you could have some detailed information, if this is the language you are working on.

We will try to see as well if the study points can be accessed separately using new properties, but we hope with little extraction logic, others can do this without much trouble from the already parsed data.

Thank you.

**Comment by HanslettTheDev** [comment]
Yes, if you can add the language for enhanced parsing, that will be great 
Thank you
